spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_social?useSSL=false
    username: root
    password: 1201harley

jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

security:
  oauth2:
    client:
      registration:
        google:
          clientId: ---------------
          clientSecret: ------------
          redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - email
            - profile
        github:
          clientId: ---------------
          clientSecret: ------------
          redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - user:email
            - read:user

app:
  auth:
    tokenSecret: --------------
    tokenExpirationMsec: 86400000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect